#
# Unprivileged BPF config file access.
#

- kind: unprivileged_bpf_config_access
  name: unprivileged_bpf_config_access
  enabled: false
  version: 1.0
  description: Unprivileged BPF config file access
  documentation: |
    https://garnet.gitbook.io/jibril/detections/file-access/unprivileged_bpf_config_access
  breed: file_access
  mechanism: file_access
  tactic: defense_evasion
  technique: impair_defenses
  subtechnique: none
  importance: high
  times:
    - kind: times_per_proc
      max: 2
    - kind: times_per_exe
      max: 4
    - kind: times_per_full_ancestry
      max: 4
  arbitrary: []
  file_actions: access_related
  file_actions_how: any
  bases:
    - dir: /proc/sys/kernel
      base: unprivileged_bpf_disabled
